### ISSUE TITLE
Move assets pipeline from CMake into Python tooling for VS compatibility

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/32blit-beta#212]
CMake seems to be more trouble than its worth when attempting to implement our ideal assets pipeline. It makes configuring assets difficult, and supporting new features or edge cases basically impossible.

I motion for a move to expanding the Python `asset-packer` tool into something that can manage the complete pipeline from configuration to asset output and be used both in Visual Studio, CMake and separately for prepping out-of-source binary blob assets (for loading off SD card for example).

## Foundational work:

- [x] refactor `sprite-builder` so that it can be imported into the asset builder and run on files directly without invoking a sub command
  - [x] support raw output
  - [x] support C-header output
- [x] refactor `map-builder` removing all the gymnatics for `Tiled` and just support converting `.tmx` to binary directly in Python... I mean they're just CSV wrapped in XML
  - [x] support raw output
  - [x] support C-header output
  - [ ] needs to be extensible enough to support new map formats
- [x] create `image-builder` for packing raw image data (RGB, RGBA)
  - [x] support raw output
  - [x] support C-header output

## Asset Builder MVP list:

New tool `asset-builder`:

- [x] update asset-packer to understand a `config.yml` or otherwise format
- [x] output to `assets.hpp` and `assets.cpp` (more complex projects may need to use assets across compilation units, so they shouldn't always be inlined into the header file?)
- [x] optional output to individual packaged binary files for streaming off SD card
- [x] multiple input files of multiple types
- [x] multiple output files of multiple types
- [x]  glob inputs, eg; `images/*.png`
- [x] asset-specific arguments such as custom names, output file groups, and other conveniences

The objective should be to make `asset-packer` super simple for a beginner to pack a couple of asset files with, but extremely deep when it's required to do something more complicated.

A basic use-case should probably auto-detect most of the asset types and act accordingly:

```
asset-packer assets/*
>> found assets/sprites.png - assuming packed spritesheet
>> found assets/level.tmx - assuming Tiled level data
>> generating assets.cpp
>> generating assets.hpp
>> Use your sprites: `screen.sprites = SpriteSheet::load((const uint8_t *)assets_sprites.data)`
>> Use your level: `level = new TileMap((uint8_t *)assets_level.data, nullptr, Size(64, 64), screen.sprites);`
```

**Comment by Daft-Freak** [comment]
Hmm, didn't think it was that bad, but interested to see what the new version looks like. BTW, the `(const uint8_t *)` cast is redundant.

**Comment by Gadgetoid** [comment]
It certainly works, and works really well in CMake, but that doesn't translate so easily to Visual Studio (or maybe even other compile methods in future).

It's also just a little unmaintainable.

I'm currently working with an `assets.yml` that looks like this, and should satisfy all cases:

```yml
# Define an output target for the asset builder
# in this case we want a c_header (and implicitly also an object file)
# type auto-detection will notice the ".hpp" and act accordingly
assets.hpp:
  # Include assets/sprites.png
  # and place it in a variable named "sprites"
  # Since it ends in ".png" the builder will run "sprites_packed" to convert our source file
  assets/sprites.png: sprites

  # Include assets/level.tmx
  # and place it in a variable named "level"
  assets/level.tmx:
    name: level

  # Slurp up all of our .bin files and leave the auto-naming on
  assets/*.bin:

  # All of our .donkey files should be joined together
  # and placed in a variable named "donkey"
  assets/*.donkey:
    name: donkey
    join: true
```

It supports:
- Inferring output type, or explicit output types of 'hpp' or 'raw'
- Inferring input type, or explicit input types of 'sprite_packed', 'map_tiled' etc
- Single files, automatically or explicitly named
- Multiple files, automatically named
- Multiple files concatenated together and automatically or explicitly named
