### ISSUE TITLE
Asset header file generation appears to be broken for small png's

### ISSUE THREAD

**Issue by ptbw** [pimoroni/32blit-beta#313]
Size of packed sprite data for small png's  appears to be wrong, header file generated shows 0x0d but size is actually 0x45. Attached is a png for a ball. Larger sprites (>255 bytes??) don't share the same issue.
(Still trying to track this down, but recording it here in case I am misunderstanding.)

![ball](https://user-images.githubusercontent.com/590409/83360818-04cc6e00-a37c-11ea-916f-5793b0b9178c.png)

**assets.yml**
```
assets.hpp:
    assets/ball.png:
        name: m_sprite_ball
        transparent: 0,0,0
```
**assets.hpp**
```
inline const uint8_t m_sprite_ball[] = {
    0x53, 0x50, 0x52, 0x49, 0x54, 0x45, 0x50, 0x4b,
    0x0d, 0x00,  // Size????
```
